name: Security scans

on:
  pull_request: { }
  push:
    branches: [ main ]

jobs:
  snyk:
    name: Run Snyk security scans
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk Code
        uses: snyk/actions/python-3.10@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      #      - name: Run Snyk Container
      #        uses: snyk/actions/docker@master
      #        continue-on-error: true
      #        with:
      #          image: ghcr.io/kvdomingo/devsecops-play
      #          args: --file=Dockerfile
      #
      #      - name: Upload result to GitHub Code Scanning
      #        uses: github/codeql-action/upload-sarif@v3
      #        with:
      #          sarif_file: snyk.sarif

      - name: Run Snyk IaC
        uses: snyk/actions/iac@master
        continue-on-error: true
        with:
          file: terraform
          args: --report

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  bandit:
    name: Run Bandit security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shundor/python-bandit-scan@v1.0
        with:
          path: "."
          exit_zero: true

  hadolint:
    name: Run Hadolint scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  gitleaks:
    name: Run Gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
